-- CREATE TABLE currency (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(50) NOT NULL UNIQUE,    
--     code CHAR(3) NOT NULL UNIQUE,        
--     symbol VARCHAR(5) DEFAULT NULL       
-- );
