-- INSERT INTO currency (name, code, symbol) VALUES ('Bolívar Venezolano', 'VES', 'Bs.');
-- INSERT INTO currency (name, code, symbol) VALUES ('Peso Colombiano', 'COP', '$');
-- INSERT INTO currency (name, code, symbol) VALUES ('Sol Peruano', 'PEN', 'S/.');
-- INSERT INTO currency (name, code, symbol) VALUES ('Peso Argentino', 'ARS', '$');
